# basic package information
name = "LazySets"
uuid = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
version = "1.3.0"
author = ["Marcelo Forets",
          "Christian Schilling",
          "Frédéric Viry"]

[deps]
# add dependencies here
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Expokit = "a1e7a1ef-7a5d-5822-a38c-be74e1bb89f4"
GLPKMathProgInterface = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
# fix dependency versions here
Compat = "1.0"
Expokit = "0.2"
GLPKMathProgInterface = "0.4"
GR = "0.32"
IntervalArithmetic = "0.14"
MathProgBase = "0.7"
Plots = "0.19"
RecipesBase = "0.5"
Requires = "0.5"

[extras]
# MyPackage = "my_uuid"

[targets]
# add targets here, e.g., for testing (define new packages under 'extras')
# test = ["MyPackage"]
